# Generated by Django 5.2.8 on 2026-01-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
