# Generated by Django 5.2.8 on 2026-01-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_author_birth_date_delete_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
