# Generated by Django 5.2.8 on 2026-01-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
