# Generated by Django 5.2.8 on 2026-01-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articlestag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlesTag',
            new_name='ArticleTag',
        ),
    ]
