# Generated by Django 5.2.8 on 2026-01-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_article_tags_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='article_tags',
        ),
    ]
