# Generated by Django 5.2.8 on 2026-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_tags_article_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(related_name='tags', to='news.articletag'),
        ),
    ]
