# Generated by Django 5.2.8 on 2026-02-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(related_name='articles', to='news.articletag'),
        ),
    ]
