# Generated by Django 5.2.8 on 2026-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=64, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, verbose_name='Почта'),
        ),
    ]
