# Generated by Django 5.2.8 on 2026-03-13 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, validators=[django.core.validators.MaxLengthValidator(128, message='Не более 128 символов.')], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.MaxLengthValidator(64, message='Не более 64 символов.')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.MaxLengthValidator(64, message='Не более 64 символов.')], verbose_name='Фамилия'),
        ),
    ]
