# Generated by Django 5.2.8 on 2026-03-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия'),
        ),
    ]
