# Generated by Django 5.2.8 on 2025-12-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
