# Generated by Django 5.2.8 on 2025-12-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
