# Generated by Django 5.2.8 on 2025-12-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_product_image_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplies',
            field=models.BooleanField(default=True),
        ),
    ]
