# Generated by Django 5.2.8 on 2025-12-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0008_product_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(default='The description and specifications are temporarily unavailable.'),
        ),
    ]
